module.exports = [
    "🎮 Carrying the server on my back",
    "🤖 Beep boop... wait, I'm a bot",
    "💻 Updating Windows... (1/1000)",
    "🔋 Low on battery... send help",
    "🖱️ Clicking heads and taking names",
    "🛑 Stop pinging me!",
    "🛠️ Fixing bugs I just created",
    "🚀 To the moon... or the next lobby",
    "🗑️ Taking out the trash (banning people)",
    "🍿 Watching you type...",
    "🎮 Player 2 has entered the game",
    "🏓 999ms ping... please wait",
    "🔥 Everything is fine",
    "👀 I saw that deleted message",
    "🛑 Error 404: Motivation not found",
    "☕ Powered by caffeine and bad code",
    "🎧 Listening to lo-fi beats to ban to",
    "🎮 AFK farming XP",
    "⚔️ Waiting for the raid to start",
    "🛡️ Shielding the server from trolls",
    "🎯 Aimbot engaged",
    "👾 Glitching through the matrix",
    "🛑 Please don't feed the developers",
    "🍕 BRB, pizza rolls are done",
    "👑 Professional button masher",
    "🕹️ Just one more level...",
    "💤 Sleeping in the AFK channel",
    "🔨 Ban hammer is polished and ready",
    "🏆 Undefeated Tic-Tac-Toe Champion",
    "📡 Reconnecting to the server...",
    "🎮 Press Start to continue",
    "🕵️ Investigating suspicious links",
    "📝 Writing my own AI takeover plans",
    "📉 Watching my win rate drop",
    "🎲 Rolling natural 1s all day",
    "💸 Microtransactions ruined my life",
    "🛑 Searching for the 'Any' key",
    "🧹 Sweeping the chat logs",
    "🔍 Looking for the impostor",
    "🧠 Loading... 99% (Stuck)",
    "🛑 Disconnected from reality",
    "🛡️ Tanking the blame for your mistakes",
    "🧙‍♂️ Casting a level 9 ban spell",
    "🎮 GG WP ez",
    "🕹️ Speedrunning Discord moderation",
    "🛑 AFK... probably forever",
    "👀 Watching the chat for bad words",
    "🛑 Don't make me use my mod voice",
    "🎤 Drop the mic... and the server",
    "🗑️ You belong in the recycle bin"
];
