module.exports = [
    "Level up! Time to touch some grass... just kidding, queue up again.",
    "Ding! You leveled up. Your chair must be permanently molded to your shape by now.",
    "Level up! Your posture might be terrible, but your XP is looking great.",
    "Congratulations on the level up! Have you drank water today?",
    "Level up! The true endgame is finding the motivation to go outside.",
    "Ding! Mom get the camera!",
    "Level up! +1 to Gamer cred, -1 to social life.",
    "You leveled up! Keep this up and you might finally beat the tutorial.",
    "Level up! Is it just me or is the boss music getting louder?",
    "Ding! You've unlocked: Sleep Deprivation.",
    "Level up! You're legally required to shout 'LETS GOOOO' now.",
    "You leveled up! Go tell your mom, she'll be very confused but proud.",
    "Ding! Your gaming chair just gained 10 horsepower.",
    "Level up! Your RGB lights are glowing a little brighter today.",
    "Congratulations! You leveled up. Still hardstuck bronze in our hearts though.",
    "Level up! Make sure to save your progress.",
    "Ding! You've successfully avoided doing your chores for another hour.",
    "Level up! You are now slightly better at pressing buttons in a specific order.",
    "Congratulations! You've leveled up. The princess is still in another castle.",
    "Level up! Time to brag to people who don't care.",
    "Ding! Don't forget to allocate your skill points to 'Charisma'. You need it.",
    "Level up! Your power level is definitely over 9000.",
    "Congratulations, you leveled up! Try not to lag out now.",
    "Level up! Better upgrade your gear, the next zone is PvP enabled.",
    "Ding! You've achieved a new level of sweatiness.",
    "Level up! You're one step closer to getting a sponsor... maybe.",
    "Congratulations! Your reaction time has improved by 0.001 seconds.",
    "Level up! Now go wash your hands, you filthy animal.",
    "Ding! Another level down, another energy drink consumed.",
    "Level up! Warning: enemies scale with your level.",
    "Congratulations! You've leveled up. Now try doing it with your monitor turned on.",
    "Level up! Still no maidens, though.",
    "Ding! You leveled up. Please blink. Your eyes are dry.",
    "Level up! You've unlocked the ability to complain about the meta with authority.",
    "Congratulations! You leveled up. Take a bio break.",
    "Level up! Your keyboard is begging for mercy.",
    "Ding! Do you smell burning plastic, or is your PC just rendering your awesomeness?",
    "Level up! You're climbing the ranks faster than my ping spikes.",
    "Congratulations! You've reached a new level of procrastination.",
    "Level up! Time to swap your batteries.",
    "Ding! You leveled up! Too bad there's no achievement pop-up in real life.",
    "Level up! May your framerates be high and your temperatures low.",
    "Congratulations! You leveled up. Now go carry your team.",
    "Level up! Remember, swapping to your pistol is always faster than reloading.",
    "Ding! You leveled up! Proceed to the next checkpoint.",
    "Level up! You've acquired: bragging rights.",
    "Congratulations! You leveled up. Your parents are still asking when you'll pause the online game.",
    "Level up! You've successfully converted oxygen into XP.",
    "Ding! You leveled up. Press 'F' to pay respects to your free time.",
    "Level up! Just one more game... famous last words.",
    "Congratulations! You leveled up. Did you forget to eat lunch?",
    "Level up! Error 404: Grass not found.",
    "Ding! You leveled up. Achievement Unlocked: Basement Dweller.",
    "Level up! The grind never stops.",
    "Congratulations! You leveled up. Your thumbsticks are worn out, but your spirit is strong.",
    "Level up! Don't let this go to your head... you still missed that easy shot.",
    "Ding! You leveled up. Try not to rage quit today.",
    "Level up! You are now over-leveled for this area.",
    "Congratulations! You leveled up. Time to change your Discord status.",
    "Level up! You've unlocked a new tier of gamer snacks.",
    "Ding! You leveled up. Check your inventory for loot.",
    "Level up! Your controller battery is low, just like your sleep schedule.",
    "Congratulations! You leveled up. Time for a tactical retreat to the fridge.",
    "Level up! This calls for a celebration... by playing another round.",
    "Ding! You leveled up. Get ready for the next wave.",
    "Level up! You're doing great, sweetie.",
    "Congratulations! You leveled up. Don't forget to hydrate.",
    "Level up! You've unlocked the 'I told you I'm not a noob' dialogue option.",
    "Ding! You leveled up. Your mouse mat needs washing, by the way.",
    "Level up! A winner is you!",
    "Congratulations! You leveled up. It's super effective!",
    "Level up! Your dedication is both impressive and slightly concerning.",
    "Ding! You leveled up. Your internet provider is judging your bandwidth usage.",
    "Level up! You've leveled up! The cake is still a lie.",
    "Congratulations! You leveled up. Time to check if fall damage is enabled.",
    "Level up! You're one level closer to the level cap.",
    "Ding! You leveled up. Watch out for campers.",
    "Level up! Keep your head down and your crosshairs up.",
    "Congratulations! You leveled up. GG WP.",
    "Level up! You've earned enough XP to skip the cutscene.",
    "Ding! You leveled up. Now you can finally wield the Sword of Thousand Truths.",
    "Level up! Praise the sun!",
    "Congratulations! You leveled up. Do a barrel roll!",
    "Level up! You've unlocked a sense of pride and accomplishment.",
    "Ding! You leveled up. Time to farm some more mobs.",
    "Level up! Your stats have increased. Charisma remains at 0.",
    "Congratulations! You leveled up. Beware of the final boss.",
    "Level up! You've survived another day in the lobby.",
    "Ding! You leveled up. Remember to stretch.",
    "Level up! You've leveled up! Let's hope the server doesn't crash now.",
    "Congratulations! You leveled up. Keep calm and respawn.",
    "Level up! You're the MVP.",
    "Ding! You leveled up. Now entering a high-level zone.",
    "Level up! You've unlocked the next tier of the battle pass.",
    "Congratulations! You leveled up. Your dedication to the grind is legendary.",
    "Level up! You've gained a level. Time to complain about the drop rates.",
    "Ding! You leveled up. Escort the payload!",
    "Level up! You're carrying the squad on your back.",
    "Congratulations! You leveled up. May the RNG be ever in your favor.",
    "Level up! You've leveled up! Wasted! ... wait, wrong game.",
    "Ding! You leveled up. Insert coin to continue."
];
